### ISSUE TITLE
More info about your setup

### ISSUE THREAD

**Issue by panigrc** [cytopia/i3-utils#1]
Hi @cytopia,
I want also to switch to I3 so it would help me if you would write more about your setup.
For example, which distro, desktop mananger, etc. you used.

Thanx.

**Comment by panigrc** [comment]
Oh ok I noticed that in https://www.everythingcli.org/my-gear/ you mention that you are using Debian 8

**Comment by cytopia** [comment]
@panigrc 
That's a bit outdated. You can find everything defined as Infrastructure as Code here: https://github.com/cytopia/ansible-debian

And then for the look and feel after the initial provision you can find my dotfiles here: https://github.com/cytopia/dotfiles

Also holds some pictures

**Comment by panigrc** [comment]
I suppose I can use your dotfiles without provisioning my system with Ansible, because I don't know if is going to be useful provisioning my personal laptop
